# Generated by Django 3.1.4 on 2022-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20220506_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='coord_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='coord_lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True),
        ),
    ]
