# Generated by Django 3.1.4 on 2022-05-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('read', '0003_auto_20220506_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(blank=True, choices=[(1, 'FULL'), (2, 'EMPTY')], default=1, max_length=1)),
                ('is_viewed', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('read', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sensor', to='read.readingssensor')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
    ]
