# Generated by Django 3.1.4 on 2022-05-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='added_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
