# Generated by Django 3.1.4 on 2022-05-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20220506_1248'),
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingsPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('power_out', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_power', to='node.nodes')),
            ],
            options={
                'verbose_name_plural': 'Readings Power',
                'db_table': 'readings_power',
            },
        ),
        migrations.CreateModel(
            name='ReadingsSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_sensor', to='node.nodes')),
            ],
            options={
                'verbose_name_plural': 'Readings Sensor',
                'db_table': 'readings_sensor',
            },
        ),
        migrations.DeleteModel(
            name='Readings',
        ),
    ]
