# Generated by Django 3.1.4 on 2022-05-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_auto_20220506_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingssensor',
            old_name='temperature',
            new_name='dust',
        ),
    ]
