# Generated by Django 3.1.4 on 2022-05-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20220506_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingspower',
            old_name='power_out',
            new_name='power_ex',
        ),
    ]
