# Generated by Django 3.1.4 on 2022-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_readingssensor_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingssensor',
            old_name='dust',
            new_name='dust1',
        ),
        migrations.AddField(
            model_name='readingssensor',
            name='dust2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
